##################################################################
# The Kernel part

include $(M)/../config.alpha.sta.mk

EXTRA_CFLAGS = -I$(M)/../rt2860v2/include
##################################################################
# We define 'CONFIG_RALINK_RT3662_2T2R' from Kernel, so mark it.
##################################################################
ifeq ($(CONFIG_RALINK_RT3662_2T2R),y)
EXTRA_CFLAGS += -DCONFIG_RALINK_RT3662_2T2R
endif

#EXTRA_CFLAGS = -DCONFIG_RALINK_RT3662_2T2R

obj-m += rt2860v2_sta.o
##################################################################
# What we add & modify are end here
# Joan Wang <joan_wang@alphanetworks.com>
##################################################################
rt2860v2_sta-objs += ../rt2860v2/common/crypt_md5.o
rt2860v2_sta-objs += ../rt2860v2/common/crypt_sha2.o
rt2860v2_sta-objs += ../rt2860v2/common/crypt_hmac.o
rt2860v2_sta-objs += ../rt2860v2/common/mlme.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_wep.o
rt2860v2_sta-objs += ../rt2860v2/common/action.o
rt2860v2_sta-objs += ../rt2860v2/common/ba_action.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_data.o
rt2860v2_sta-objs += ../rt2860v2/common/rtmp_init.o
rt2860v2_sta-objs += ../rt2860v2/common/rtmp_init_inf.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_tkip.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_aes.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_sync.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_sanity.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_info.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_wpa.o
rt2860v2_sta-objs += ../rt2860v2/common/dfs.o
#rt2860v2_sta-objs += ../rt2860v2/common/dfs_mcu.o
rt2860v2_sta-objs += ../rt2860v2/common/spectrum.o

rt2860v2_sta-objs += ../rt2860v2/common/rtmp_timer.o
rt2860v2_sta-objs += ../rt2860v2/common/rt_channel.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_profile.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_asic.o
rt2860v2_sta-objs += ../rt2860v2/common/rtmp_swmcu.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_cfg.o
rt2860v2_sta-objs += ../rt2860v2/common/eeprom.o
rt2860v2_sta-objs += ../rt2860v2/common/ee_flash.o


rt2860v2_sta-objs += ../rt2860v2/common/cmm_mac_pci.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_data_pci.o
rt2860v2_sta-objs += ../rt2860v2/common/crypt_aes.o
rt2860v2_sta-objs += ../rt2860v2/common/crypt_arc4.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_cmd.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_wpa_adhoc.o

rt2860v2_sta-objs += ../rt2860v2/sta/assoc.o
rt2860v2_sta-objs += ../rt2860v2/sta/auth.o
rt2860v2_sta-objs += ../rt2860v2/sta/auth_rsp.o
rt2860v2_sta-objs += ../rt2860v2/sta/sync.o
rt2860v2_sta-objs += ../rt2860v2/sta/sanity.o
rt2860v2_sta-objs += ../rt2860v2/sta/rtmp_data.o
rt2860v2_sta-objs += ../rt2860v2/sta/connect.o
rt2860v2_sta-objs += ../rt2860v2/sta/wpa.o
rt2860v2_sta-objs += ../rt2860v2/sta/sta_cfg.o

rt2860v2_sta-objs +=  ../rt2860v2/os/linux/rt_proc.o
rt2860v2_sta-objs +=  ../rt2860v2/os/linux/rt_linux.o
rt2860v2_sta-objs +=  ../rt2860v2/os/linux/rt_profile.o
rt2860v2_sta-objs +=  ../rt2860v2/os/linux/rt_main_dev.o
rt2860v2_sta-objs +=  ../rt2860v2/os/linux/sta_ioctl.o
rt2860v2_sta-objs += ../rt2860v2/common/rt_ate.o


rt2860v2_sta-objs +=  ../rt2860v2/os/linux/rbus_main_dev.o
rt2860v2_sta-objs +=  ../rt2860v2/os/linux/rt_pci_rbus.o
rt2860v2_sta-objs += ../rt2860v2/os/linux/rt_rbus_pci_util.o

ifeq ($(CONFIG_SMART_ANTENNA),y)
#//+++Add by bouble for Smart Antenna
#rt2860v2_sta-objs += ../rt2860v2/common/smartant_sta.o
ifdef SMART_ANTENNA_OBJECT
#rt2860v2_sta-objs += ../rt2860v2/common/smartant_sta.o
rt2860v2_sta-objs += ../rt2860v2/common/$(SMART_ANTENNA_OBJECT)
else
rt2860v2_sta-objs += ../rt2860v2/common/smartant_sta.o
endif
#//---Add by bouble for smart Antenna 
endif

ifeq ($(CONFIG_RALINK_RT2880),y)
rt2860v2_sta-objs +=  ../rt2860v2/chips/rt2880.o
endif

ifeq ($(CONFIG_RALINK_RT2883),y)
rt2860v2_sta-objs +=  ../rt2860v2/common/rt_rf.o
rt2860v2_sta-objs +=  ../rt2860v2/chips/rt2883.o
ifeq ($(CONFIG_RT2860V2_STA_TXBF),y)
rt2860v2_sta-objs +=  ../rt2860v2/common/cmm_txbf.o
rt2860v2_sta-objs +=  ../rt2860v2/common/cmm_txbf_cal.o
endif
endif

ifeq ($(CONFIG_RALINK_RT3883),y)
rt2860v2_sta-objs +=  ../rt2860v2/common/rt_rf.o
rt2860v2_sta-objs +=  ../rt2860v2/chips/rt3883.o
ifeq ($(CONFIG_RT2860V2_STA_TXBF),y)
rt2860v2_sta-objs +=  ../rt2860v2/common/cmm_txbf.o
rt2860v2_sta-objs +=  ../rt2860v2/common/cmm_txbf_cal.o
endif
endif

ifeq ($(CONFIG_RALINK_RT3052),y)
rt2860v2_sta-objs +=  ../rt2860v2/common/rt_rf.o
rt2860v2_sta-objs +=  ../rt2860v2/chips/rt305x.o
endif

ifeq ($(CONFIG_RALINK_RT3352),y)
rt2860v2_sta-objs +=  ../rt2860v2/common/rt_rf.o
rt2860v2_sta-objs +=  ../rt2860v2/chips/rt305x.o
endif

ifeq ($(CONFIG_RT2860V2_STA_LED),y)
rt2860v2_sta-objs += ../rt2860v2/common/led.o
endif

ifeq ($(CONFIG_RT2860V2_STA_WMM_ACM),y)
rt2860v2_sta-objs += ../rt2860v2/common/acm_edca.o
rt2860v2_sta-objs += ../rt2860v2/common/acm_comm.o
rt2860v2_sta-objs += ../rt2860v2/common/acm_iocl.o
endif

#ifeq ($(CONFIG_RT2860V2_STA_WAPI),y)
#rt2860v2_sta-objs += wapi.obj
#rt2860v2_sta-objs += wapi_sms4.obj
#rt2860v2_sta-objs += wapi_crypt.obj
#endif

#ifeq ($(CONFIG_RT2860V2_RT3XXX_STA_ANTENNA_DIVERSITY),y)
#rt2860v2_sta-objs += ../rt2860v2/os/linux/ap_diversity.o
#endif

ifeq ($(CONFIG_RT2860V2_STA_MESH),y)
rt2860v2_sta-objs += ../rt2860v2/common/mesh_bmpkt.o
rt2860v2_sta-objs += ../rt2860v2/common/mesh_ctrl.o
rt2860v2_sta-objs += ../rt2860v2/common/mesh_link_mng.o
rt2860v2_sta-objs += ../rt2860v2/common/mesh_sanity.o
rt2860v2_sta-objs += ../rt2860v2/common/mesh_tlv.o
rt2860v2_sta-objs += ../rt2860v2/common/mesh.o
rt2860v2_sta-objs += ../rt2860v2/common/mesh_inf.o
rt2860v2_sta-objs += ../rt2860v2/common/mesh_forwarding.o
rt2860v2_sta-objs += ../rt2860v2/common/mesh_path_mng.o
endif

ifeq ($(CONFIG_RT2860V2_STA_DLS),y)
rt2860v2_sta-objs += ../rt2860v2/sta/dls.o
endif

ifeq ($(CONFIG_RT2860V2_STA_WSC),y)
rt2860v2_sta-objs += ../rt2860v2/common/wsc.o
rt2860v2_sta-objs += ../rt2860v2/common/wsc_tlv.o
rt2860v2_sta-objs += ../rt2860v2/common/crypt_biginteger.o
rt2860v2_sta-objs += ../rt2860v2/common/crypt_dh.o
endif

ifeq ($(CONFIG_RT2860V2_STA_ETH_CONVERT),y)
rt2860v2_sta-objs += ../rt2860v2/common/cmm_mat.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_mat_iparp.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_mat_pppoe.o
rt2860v2_sta-objs += ../rt2860v2/common/cmm_mat_ipv6.o
endif

ifeq ($(CONFIG_RT2860V2_STA_VIDEO_TURBINE),y)
rt2860v2_sta-objs += ../rt2860v2/common/cmm_video.o
endif

###################
#  CFLAGS
##################
EXTRA_CFLAGS += -DAGGREGATION_SUPPORT -DPIGGYBACK_SUPPORT -DWMM_SUPPORT  -DLINUX \
	       -Wall -Wstrict-prototypes -Wno-trigraphs 

EXTRA_CFLAGS += -DCONFIG_STA_SUPPORT -DDBG -DRALINK_ATE -DRALINK_28xx_QA -DRTMP_RBUS_SUPPORT -DRTMP_MAC_PCI -DDOT11_N_SUPPORT -DDOT11N_DRAFT3 -DRELASE_EXCLUDE
EXTRA_CFLAGS += -DSTATS_COUNT_SUPPORT -DCONFIG_RT2880_ATE_CMD_NEW 

ifeq ($(CONFIG_RALINK_RT2880),y)
EXTRA_CFLAGS += -DRT2880
endif

ifeq ($(CONFIG_RALINK_RT2883),y)
EXTRA_CFLAGS += -DRT2883 -DRTMP_RF_RW_SUPPORT -DDOT11N_SS3_SUPPORT -DCONFIG_RALINK_RT2883
ifeq ($(CONFIG_RT2860V2_STA_TXBF),y)
EXTRA_CFLAGS += -DTXBF_SUPPORT
endif
endif

ifeq ($(CONFIG_RALINK_RT3883),y)
EXTRA_CFLAGS += -DRT3883 -DRTMP_RF_RW_SUPPORT -DDOT11N_SS3_SUPPORT -DCONFIG_RALINK_RT3883
ifeq ($(CONFIG_RT2860V2_STA_TXBF),y)
EXTRA_CFLAGS += -DTXBF_SUPPORT
endif
endif

ifeq ($(CONFIG_RALINK_RT3052),y)
EXTRA_CFLAGS += -DRT3052 -DRT305x -DRTMP_RF_RW_SUPPORT
endif

ifeq ($(CONFIG_RALINK_RT3352),y)
EXTRA_CFLAGS += -DRT3352 -DRT305x -DRTMP_RF_RW_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_STA_WPA_SUPPLICANT),y)
EXTRA_CFLAGS += -DWPA_SUPPLICANT_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_STA_WMM_ACM),y)
EXTRA_CFLAGS += -DWMM_ACM_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_STA_LED),y)
EXTRA_CFLAGS += -DWLAN_LED -DLED_CONTROL_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_SNMP),y)
EXTRA_CFLAGS += -DSNMP_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_STA_CARRIER),y)
EXTRA_CFLAGS += -DCARRIER_DETECTION_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_EXT_CHANNEL_LIST),y)
EXTRA_CFLAGS   += -DEXT_BUILD_CHANNEL_LIST
endif

ifeq ($(CONFIG_RT2860V2_STA_IDS),y)
EXTRA_CFLAGS += -DIDS_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_STA_DLS),y)
EXTRA_CFLAGS += -DQOS_DLS_SUPPORT
endif

#ifeq ($(CONFIG_RT2860V2_STA_WAPI),y)
#ifeq ($(CONFIG_RALINK_RT3883),y)
#EXTRA_CFLAGS += -DWAPI_SUPPORT
#else
#EXTRA_CFLAGS += -DWAPI_SUPPORT -DSOFT_ENCRYPT
#endif
#endif

ifeq ($(CONFIG_RT2860V2_STA_MESH),y)
EXTRA_CFLAGS   += -DMESH_SUPPORT -DINTEL_CMPC
endif

ifeq ($(CONFIG_RT2860V2_RT3XXX_STA_ANTENNA_DIVERSITY),y)
EXTRA_CFLAGS   += -DRT3XXX_ANTENNA_DIVERSITY_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_STA_WSC),y)
EXTRA_CFLAGS += -DWSC_STA_SUPPORT -DWSC_LED_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_STA_ETH_CONVERT),y)
EXTRA_CFLAGS += -DETH_CONVERT_SUPPORT -DMAT_SUPPORT -DKMALLOC_BATCH
endif

ifeq ($(CONFIG_RT2860V2_STA_VIDEO_TURBINE),y)
EXTRA_CFLAGS += -DVIDEO_TURBINE_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_STA_TXBF),y)
EXTRA_CFLAGS   += -DTXBF_SUPPORT
endif

ifeq ($(CONFIG_RA_NETWORK_WORKQUEUE_BH),y)
EXTRA_CFLAGS   += -DWORKQUEUE_BH
endif

ifeq ($(CONFIG_RT2860V2_STA_INTELLIGENT_RATE_ADAPTION),y)
EXTRA_CFLAGS   += -DNEW_RATE_ADAPT_SUPPORT
endif

ifeq ($(CONFIG_USE_OUR_OWN_LIGHTING_METHOD),y)
EXTRA_CFLAGS   += -DCONFIG_USE_OUR_OWN_LIGHTING_METHOD
endif

ifeq ($(CONFIG_WLAN_LED_PRIVATE),y)
EXTRA_CFLAGS += -DCONFIG_WLAN_LED_PRIVATE
endif

ifeq ($(CONFIG_RT2860V2_ALPHA_STA_WPA_AUTO_SUPPORT),y)
EXTRA_CFLAGS   += -DALPHA_STA_WPA_AUTO_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_ALPHA_STA_CIPHER_AUTO_SUPPORT),y)
EXTRA_CFLAGS   += -DALPHA_STA_CIPHER_AUTO_SUPPORT
endif

ifeq ($(CONFIG_RT2860V2_ALPHA_STA_WSC_PIN_NO_SSID_SUPPORT),y)
EXTRA_CFLAGS   += -DALPHA_STA_WSC_PIN_NO_SSID_SUPPORT
endif

ifeq ($(CONFIG_SMART_ANTENNA),y)
#//+++Add by bouble for Smart Antenna
EXTRA_CFLAGS += -DSMART_ANTENNA -DSA_DBG -DSA_LUMP_SUM -DRELEASE_EXCLUDE
EXTRA_CFLAGS += -DFIFO_EXT_SUPPORT -DPER_MAC_FIFO
#//---Add by bouble for Smart Antenna
endif

# Freddy - 20110413 - add a wireless interface for outside commands.
ifeq ($(CONFIG_ALPHA_IOCTL_INTERFACE_SUPPORT),y)
EXTRA_CFLAGS += -DCONFIG_ALPHA_IOCTL_INTERFACE_SUPPORT
rt2860v2_sta-objs += ../rt2860v2/os/linux/alpha_ioctl.o
endif
#harry add of FCC dfs channel
ifeq ($(CONFIG_FCC_DFS_ENABLE),y)
EXTRA_CFLAGS += -DCONFIG_FCC_DFS_ENABLE
endif
#harry add for DHCP's UDP Header CheckSum re-build, replace of setting it as zero
ifeq ($(CONFIG_STA_DHCP_UDPCHECKSUM_REBUILD),y)
EXTRA_CFLAGS += -DCONFIG_STA_DHCP_UDPCHECKSUM_REBUILD
endif
ifeq ($(ELBOX_BRAND_ARIESAP_DAP1522B),y)
EXTRA_CFLAGS += -DELBOX_BRAND_ARIESAP_DAP1522B
endif

