/*
 * Automatically generated header file, don't edit!
 */
#define ELBOX_HAVE_DOT_CONFIG 1
#define ELBOX_FIRMWARE_VERSION "2.06"
#define ELBOX_FIRMWARE_REVISION "B01"

/* Device Configuration */
#define ELBOX_FIRMWARE_SIGNATURE "N/A"
#undef  ELBOX_BOARD_DEFAULT
#undef  ELBOX_BOARD_WMXRG01E
#undef  ELBOX_BOARD_WMXRG02E
#undef  ELBOX_BOARD_WMXCO02E
#undef  ELBOX_BOARD_WAPG14
#undef  ELBOX_BOARD_WAPG18
#undef  ELBOX_BOARD_WAPN03
#undef  ELBOX_BOARD_WAPN06
#undef  ELBOX_BOARD_WAPN07
#undef  ELBOX_BOARD_WAPN09
#undef  ELBOX_BOARD_WAPN10
#undef  ELBOX_BOARD_AP1525
#undef  ELBOX_BOARD_WAPND01
#undef  ELBOX_BOARD_WAPND02
#undef  ELBOX_BOARD_WAPND03
#undef  ELBOX_BOARD_WAPND03CM
#undef  ELBOX_BOARD_WAPN08
#undef  ELBOX_BOARD_WAPN11
#undef  ELBOX_BOARD_WAPN11H
#undef  ELBOX_BOARD_WAPN18
#undef  ELBOX_BOARD_WAPN12
#undef  ELBOX_BOARD_WAPND04
#undef  ELBOX_BOARD_WAPND04CM
#undef  ELBOX_BOARD_WAPND06
#undef  ELBOX_BOARD_WAPND09
#undef  ELBOX_BOARD_WAPND14
#define ELBOX_BOARD_WAPND15 1
#undef  ELBOX_BOARD_WAPND16
#undef  ELBOX_BOARD_WAPND17
#undef  ELBOX_BOARD_RG12
#undef  ELBOX_BOARD_WRGG14
#undef  ELBOX_BOARD_WRGG14C
#undef  ELBOX_BOARD_WRGG15C
#undef  ELBOX_BOARD_WRGG16
#undef  ELBOX_BOARD_WRGG19
#undef  ELBOX_BOARD_WRGG19_C
#undef  ELBOX_BOARD_WRGG19_C_ART
#undef  ELBOX_BOARD_WRGG19_C_HSPOT
#undef  ELBOX_BOARD_WRGG22
#undef  ELBOX_BOARD_WRGG23
#undef  ELBOX_BOARD_WRGG24
#undef  ELBOX_BOARD_WRGG27
#undef  ELBOX_BOARD_WRGG27HP
#undef  ELBOX_BOARD_WRGG27_3G
#undef  ELBOX_BOARD_RT3052
#undef  ELBOX_BOARD_WRGN06
#undef  ELBOX_BOARD_WRGN06C
#undef  ELBOX_BOARD_WRGN09
#undef  ELBOX_BOARD_WRGN10
#undef  ELBOX_BOARD_WRGN13
#undef  ELBOX_BOARD_WRGN15
#undef  ELBOX_BOARD_WRGN15C
#undef  ELBOX_BOARD_WRGN16
#undef  ELBOX_BOARD_WRGN16A
#undef  ELBOX_BOARD_WRGN18
#undef  ELBOX_BOARD_WRGN18N
#undef  ELBOX_BOARD_SWRGN18
#undef  ELBOX_BOARD_WRGN19
#undef  ELBOX_BOARD_WRGN20
#undef  ELBOX_BOARD_WRGN22
#undef  ELBOX_BOARD_WRGN22S
#undef  ELBOX_BOARD_WRGN23
#undef  ELBOX_BOARD_WRGN23I
#undef  ELBOX_BOARD_WRGN23TD
#undef  ELBOX_BOARD_WRGN23HA
#undef  ELBOX_BOARD_WRGN27
#undef  ELBOX_BOARD_WRGN27U
#undef  ELBOX_BOARD_WRGN28
#undef  ELBOX_BOARD_WRGN45P
#undef  ELBOX_BOARD_WRGN29
#undef  ELBOX_BOARD_WRGN34
#undef  ELBOX_BOARD_WRGN37
#undef  ELBOX_BOARD_WRGN38
#undef  ELBOX_BOARD_WRGN39
#undef  ELBOX_BOARD_WRGN49
#undef  ELBOX_BOARD_WRGN50
#undef  ELBOX_BOARD_WRGN51
#undef  ELBOX_BOARD_WRGN59
#undef  ELBOX_BOARD_WRGN62
#undef  ELBOX_BOARD_WRGND02
#undef  ELBOX_BOARD_WRGND03
#undef  ELBOX_BOARD_WRGND04
#undef  ELBOX_BOARD_WRGND06
#undef  ELBOX_BOARD_WRGND12
#undef  ELBOX_BOARD_WRGND21
#undef  ELBOX_BOARD_WRGND07
#undef  ELBOX_BOARD_WRGN42P
#undef  ELBOX_BOARD_WRGN42
#undef  ELBOX_BOARD_WRGND08
#undef  ELBOX_BOARD_WRGND09
#undef  ELBOX_BOARD_WRGND10
#undef  ELBOX_BOARD_IP8KEVAL
#undef  ELBOX_BOARD_WRGND11
#undef  ELBOX_BOARD_WRGND14
#undef  ELBOX_BOARD_WRGNS01
#undef  ELBOX_BOARD_WTDRG01
#undef  ELBOX_BOARD_WTDRV01
#undef  ELBOX_BOARD_WHDRV01
#undef  ELBOX_BOARD_WRGN33
#undef  ELBOX_BOARD_HPW310AV
#undef  ELBOX_BOARD_HPW310AV_ATHEROS
#undef  ELBOX_BOARD_WRGAC01
#define ELBOX_BOARD_NAME "wapnd15"
#define ELBOX_BSP_RT3883_KERNEL_V2_6_33 1
#define ELBOX_BSP_NAME "rt3883.kernel-2.6.33"
#define ELBOX_LINUX_MAJOR 2
#define ELBOX_LINUX_MINOR 6
#define ELBOX_LINUX_BUILD 33
#undef  ELBOX_TEMPLATE_GW_WIFI
#undef  ELBOX_TEMPLATE_GW_WIFI_2WAN
#undef  ELBOX_TEMPLATE_AP_WIFI
#undef  ELBOX_TEMPLATE_AP_WIFI_CMCC
#undef  ELBOX_TEMPLATE_AP_GW_WIFI
#undef  ELBOX_TEMPLATE_AP_GAMING
#undef  ELBOX_TEMPLATE_AP_WIFI_CLOUD
#undef  ELBOX_TEMPLATE_AP_WIFI_WAN
#undef  ELBOX_TEMPLATE_TENDER
#undef  ELBOX_TEMPLATE_EMPTY
#undef  ELBOX_TEMPLATE_ARIES
#define ELBOX_TEMPLATE_ARIES_BRIDGE_AP 1
#define ELBOX_TEMPLATE_NAME "aries.ap"
#define ELBOX_BRAND_NAME "dlob"
#define ELBOX_MODEL_NAME "dap1522b"
#define ELBOX_ARIES_SESSION_BASE "/runtime/session"
#undef  ELBOX_ARIES_USE_UDEV
#undef  ELBOX_TEMPLATE_ARIES_ENABLE_USER_MANAGEMENT

/* Aries Configuration */

/* HTTP/CGI kits */
#define ELBOX_BRAND_ARIESAP_DLOB 1
#undef  ELBOX_BRAND_ARIESAP_DAP1525
#undef  ELBOX_BRAND_ARIESAP_DAP1525B
#define ELBOX_BRAND_ARIESAP_DAP1522B 1
#undef  ELBOX_BRAND_ARIESAP_HPW310AV
#undef  ELBOX_BRAND_ARIESAP_HPW310AV_ATH

/* Features configuration */
#undef  LOGNUM
#define ELBOX_USE_IPV6 1

/* Language Configuration */

/* Language options */
#define ELBOX_CREATE_LANGUAGE_PACK 1

/* Languages */
#undef  ELBOX_LANGUAGE_EN
#undef  ELBOX_LANGUAGE_JA
#undef  ELBOX_LANGUAGE_DE
#undef  ELBOX_LANGUAGE_ZH_TW
#undef  ELBOX_LANGUAGE_ZH_CN
#undef  ELBOX_LANGUAGE_FR
#undef  ELBOX_LANGUAGE_ES
#undef  ELBOX_LANGUAGE_IT
#undef  ELBOX_LANGUAGE_NL
#undef  ELBOX_LANGUAGE_PT
#undef  ELBOX_LANGUAGE_FI
#undef  ELBOX_LANGUAGE_SV
#undef  ELBOX_LANGUAGE_NO
#undef  ELBOX_LANGUAGE_DA
#undef  ELBOX_LANGUAGE_KO
#undef  ELBOX_LANGUAGE_PL
#undef  ELBOX_LANGUAGE_RU
#undef  ELBOX_LANGUAGE_HE
#undef  ELBOX_LANGUAGE_HU
#undef  ELBOX_LANGUAGE_EL
#undef  ELBOX_LANGUAGE_TR
#undef  ELBOX_LANGUAGE_CS
#undef  ELBOX_LANGUAGE_TH
#undef  ELBOX_LANGUAGE_AR
#undef  ELBOX_LANGUAGE_IS

/* Default Language */

/* Programs Configuration */

/* GPL Programs */

/* ------------------------ Busybox ------------------------ --- */
#define ELBOX_BUSYBOX 1
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_00
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_11_1
#define ELBOX_PROGS_GPL_BUSYBOX_1_14_1 1
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_18_1
#undef  ELBOX_PROGS_GPL_ASSIGN_DEV_RUN_SHELL_ON
#undef  ELBOX_PROGS_GPL_BUSYBOX_1_14_1_NOIP
#undef  ELBOX_PROGS_GPL_BUSYBOX_NOBZIP2
#undef  ELBOX_PROGS_GPL_BUSYBOX_NO_2_4_MODULES
#undef  ELBOX_PROGS_GPL_TFTP_FTP_GET_PUT_FW_CONFIG
#undef  ELBOX_BUSYBOX_DYNAMIC_LINKING
#undef  ELBOX_BUSYBOX_HAVE_MDEV
#undef  ELBOX_BUSYBOX_USE_FANCY_PING

/* ------------------------ Programs ----------------------- --- */
#undef  ELBOX_ARP_SPOOF
#undef  ELBOX_PROGS_GPL_BPALOGIN
#undef  ELBOX_PROGS_GPL_CHILLISPOT
#undef  ELBOX_PROGS_GPL_CTORRENT
#undef  ELBOX_PROGS_GPL_DIBBLER
#undef  ELBOX_PROGS_GPL_DHCPV6_LINUX
#undef  ELBOX_USE_DNS
#undef  ELBOX_PROGS_GPL_E2FSPROGS
#undef  ELBOX_HOSTAPD
#define ELBOX_HTTPD 1
#undef  ELBOX_PROGS_GPL_MATHOPD
#undef  ELBOX_PROGS_GPL_MATHOPD_STANDARD
#define ELBOX_PROGS_GPL_MATHOPD_16 1

/* Upload externel file */
#undef  ELBOX_PROGS_GPL_MATHOPD_EXTERNAL_FILE
#undef  ELBOX_PROGS_GPL_MATHOPD_ACL_IMPORT
#undef  ELBOX_PROGS_GPL_MATHOPD_EXTERNAL_BT_FILE
#undef  ELBOX_PROGS_GPL_MATHOPD_DUAL_RUNTIME_IMAGE
#undef  ELBOX_PROGS_GPL_IGMPPROXY
#undef  ELBOX_PROGS_GPL_IPPERSONALITY
#define ELBOX_PROGS_GPL_IPROUTE2_2_6_8 1
#undef  ELBOX_PROGS_GPL_IPROUTE2_2_6_33
#define ELBOX_PROGS_GPL_TC_FOR_AP 1
#define ELBOX_PROGS_GPL_TC_U32_IP_PORT_RANGE 1
#undef  ELBOX_IPTABLES
#undef  ELBOX_PROGS_GPL_ITUNES_SERVER
#define ELBOX_MDNSRESPONDER 1
#define ELBOX_PROGS_GPL_MDNSRESPONDER_320_5_1 1
#undef  ELBOX_KLOGD
#undef  ELBOX_PROGS_GPL_LPRNG_3_8_27
#undef  ELBOX_MINIDLNA
#define ELBOX_PROGS_GPL_NSBBOX 1

/* NotSoBusyBOX configuration */
#undef  CONFIG_NSBBOX_BASE64
#define CONFIG_NSBBOX_BRCTL 1
#define CONFIG_NSBBOX_BRCTL_BWCTRL 1
#undef  CONFIG_NSBBOX_BRCTL_IOAPNL
#define CONFIG_NSBBOX_BRCTL_PORTFORWARD 1
#undef  CONFIG_NSBBOX_BRCTL_PORTDENYLIST
#undef  CONFIG_NSBBOX_BRCTL_IGMP
#undef  CONFIG_NSBBOX_BRCTL_AP_OPERATION_MODE
#undef  CONFIG_NSBBOX_BRCTL_APC_OPERATION_MODE
#undef  CONFIG_NSBBOX_BRCTL_DHCP_SERVER_ENABLE
#define CONFIG_NSBBOX_BRCTL_E_PARTITION 1
#undef  CONFIG_NSBBOX_BRCTL_ETHLINK
#undef  CONFIG_NSBBOX_BRCTL_LIMITED_ADMIN
#undef  CONFIG_NSBBOX_BRCTL_PING_CONTROL
#undef  CONFIG_NSBBOX_BRCTL_MULTI_VLAN
#undef  CONFIG_NSBBOX_BRCTL_MAT_STATUS
#undef  CONFIG_NSBBOX_BRCTL_MAC_CLONE
#define CONFIG_NSBBOX_NTPCLIENT 1
#undef  CONFIG_NSBBOX_SMTPCLIENT
#undef  CONFIG_NSBBOX_VCONFIG
#undef  CONFIG_NSBBOX_BRCTL_FORWARDING_DB
#undef  ELBOX_PPPD
#undef  ELBOX_PROGS_GPL_PURE_FTPD
#undef  ELBOX_PROGS_GPL_QUAGGA
#undef  ELBOX_PROGS_GPL_QUOTA
#undef  ELBOX_PROGS_GPL_RADVD
#undef  ELBOX_PROGS_GPL_RADVD_1_7
#undef  ELBOX_PROGS_GPL_RADVD_1_8
#undef  ELBOX_PROGS_GPL_NTFS_3G
#undef  ELBOX_SAMBA
#undef  ELBOX_PROGS_GPL_SFDISK
#undef  ELBOX_PROGS_GPL_NET_SNMP
#undef  ELBOX_AP_WLAN_TELECOM_STATISTIC
#undef  ELBOX_PROGS_GPL_STUPID_FTPD
#undef  ELBOX_USE_SYSLOG
#undef  ELBOX_PROGS_GPL_TELNETD
#undef  ELBOX_PROGS_GPL_TINYLOGIN
#undef  ELBOX_TSPC
#undef  ELBOX_PROGS_GPL_TZCOMPILER
#define ELBOX_PROGS_GPL_UDEV 1
#define ELBOX_UDHCP 1

/* Use Unicasting and broadcasting request */
#undef  ELBOX_PROGS_GPL_UDHCP_REQUEST_BROADCAST
#undef  ELBOX_PROGS_GPL_UDHCP_0_9_8
#define ELBOX_PROGS_GPL_UDHCPCD 1
#undef  ELBOX_PROGS_GPL_UDHCP_RFC3442
#undef  ELBOX_PROGS_GPL_UDHCP_MS_RFC3442
#undef  ELBOX_PROGS_GPL_UDHCP_RFC2132
#undef  ELBOX_PROGS_GPL_UDHCP_HOLD_LAN_IP
#undef  ELBOX_PROGS_GPL_UPNPIGD
#undef  ELBOX_PROGS_GPL_USB_MODE_SWITCH
#undef  ELBOX_PROGS_GPL_WOL
#define ELBOX_PROGS_GPL_WIDE_DHCPV6 1
#define ELBOX_PROGS_GPL_WIRELESS_TOOLS 1

/* IWLIST configuration */
#undef  CONFIG_IWLIST_APSCANN

/* IWPRIV configuration */
#undef  CONFIG_IWPRIV_APSCAN
#undef  ELBOX_PROGS_GPL_WIRELESS_TOOLS_REALTEK_29
#undef  ELBOX_PROGS_GPL_XSUPPLICANT
#undef  ELBOX_PROGS_GPL_ZEBRA
#undef  ELBOX_RADIUSCLIENT
#undef  ELBOX_PROGS_GPL_ECMH
#undef  ELBOX_PROGS_GPL_IPUTILS
#define ELBOX_PROGS_GPL_NDISC6_0_9_9 1
#undef  ELBOX_PROGS_GPL_UPNPC
#undef  ELBOX_PROGS_GPL_BDB
#undef  ELBOX_PROGS_GPL_IMAGE_TOOLS
#undef  ELBOX_PROGS_GPL_ZIP

/* ------------------------ Libraries ------------------------ --- */
#undef  ELBOX_FLEX
#undef  ELBOX_LIBNL
#undef  ELBOX_PROGS_GPL_LIB_GSASL
#undef  ELBOX_OPENSSL
#undef  ELBOX_PROGS_GPL_LIBTORRENT
#undef  ELBOX_ZLIB
#undef  ELBOX_PROGS_GPL_EMAILCLIENT
#undef  ELBOX_PROGS_GPL_EBTABLES
#undef  ELBOX_PROGS_GPL_CLOUD_MANAGE_UPDATEFW
#undef  ELBOX_PROGS_GPL_LIBICONV_1_9_1
#undef  ELBOX_SQLITE

/* Private Programs (developed by AlphaNetworks) */
#undef  ELBOX_PROGS_PRIV_CALLMGR
#define ELBOX_XMLDB 1
#undef  ELBOX_PROGS_PRIV_XMLDB
#define ELBOX_PROGS_PRIV_XMLDB3 1
#define ELBOX_PROGS_PRIV_RGBIN 1

/* RGBIN configuration */

/* GPL tools - DO NOT use the GPL code here, use PROG.GPL/NSBBOX instead !! */
#undef  CONFIG_RGBIN_BASE64
#undef  CONFIG_RGBIN_BRCTL
#undef  CONFIG_RGBIN_PING_CONTROL_USE_PROC_FILE
#undef  CONFIG_RGBIN_NTPCLIENT
#undef  CONFIG_RGBIN_SMTPCLIENT
#undef  CONFIG_RGBIN_VCONFIG
#undef  CONFIG_RGBIN_BRCTL_WEB_REDIRECT

/* Private tools - ONLY use the private code here !! */
#define CONFIG_RGBIN_SEAMA 1
#define CONFIG_RGBIN_HTTPC 1
#define CONFIG_RGBIN_GENUUID 1
#define CONFIG_RGBIN_PFILE 1
#define CONFIG_RGBIN_SCUT 1
#undef  CONFIG_RGBIN_TLOGS
#undef  CONFIG_RGBIN_ASESSION
#undef  CONFIG_RGBIN_MPCONVERT
#undef  CONFIG_RGBIN_DAYCONVERT
#undef  CONFIG_RGBIN_CHNET
#undef  CONFIG_RGBIN_ROUTETABLE
#undef  CONFIG_RGBIN_PARSEINFO
#define CONFIG_RGBIN_LOGIN 1
#undef  CONFIG_RGBIN_ARPPING
#undef  CONFIG_RGBIN_GETHOSTIP
#define CONFIG_RGBIN_GETBOOTVER 1
#undef  CONFIG_RGBIN_COREDE
#define CONFIG_RGBIN_USOCKC 1
#define CONFIG_RGBIN_SUSOCKC 1
#undef  CONFIG_RGBIN_RSTRCMP
#undef  CONFIG_RGBIN_GETSYS
#undef  CONFIG_RGBIN_USB3G_KIT
#undef  CONFIG_RGBIN_REMSERIAL
#undef  CONFIG_RGBIN_USBRESET
#undef  CONFIG_RGBIN_CHECK_CONNECTION
#undef  CONFIG_RGBIN_3GCHAT
#undef  CONFIG_RGBIN_SIMUNLOCK
#define CONFIG_RGBIN_IPV6IP 1
#define CONFIG_RGBIN_IPV6PDIP 1
#undef  CONFIG_RGBIN_EUI64
#undef  CONFIG_RGBIN_SENDTRAP
#undef  CONFIG_RGBIN_SYSLOGMSG
#undef  CONFIG_RGBIN_MEMTEST
#undef  CONFIG_RGBIN_FLASHTEST

/* DevData - Permanent Data */
#define CONFIG_RGBIN_DEVDATA 1
#define CONFIG_RGBIN_DEVDATA_MTDBLOCK "/dev/mtdblock/4"
#define CONFIG_RGBIN_DEVDATA_OFFSET 0x8000
#define CONFIG_RGBIN_DEVDATA_SIZE 0x8000

/* DevConf - User Configuration */
#define CONFIG_RGBIN_DEVCONF 1
#define CONFIG_RGBIN_DEVCONF_MTDBLOCK "/dev/mtdblock/3"
#define CONFIG_RGBIN_DEVCONF_OFFSET 0x0
#define CONFIG_RGBIN_DEVCONF_SIZE 0x10000

/* outdated utilities */
#undef  ELBOX_RGBIN_RGCFG
#undef  CONFIG_RGBIN_RGDB
#define CONFIG_RGBIN_TCPREQUEST 1
#undef  CONFIG_RGBIN_SCHEDULE_FOR_NTP_CONNECT_COUNTER
#undef  CONFIG_RGBIN_LOGIN_HIDE_PASSWORD
#undef  ELBOX_ALPHA_XGI
#undef  ELBOX_IPSEC_PT
#define ELBOX_IFRESETCNT 1
#undef  ELBOX_PROGS_PRIV_IFRESETCNT
#define ELBOX_PROGS_PRIV_IFRESETCNT_26 1
#undef  ELBOX_STUN_NAT
#undef  ELBOX_TURBONAT
#undef  ELBOX_PROGS_PRIV_BWC
#undef  ELBOX_PROGS_PRIV_FLOWMETER
#undef  ELBOX_PROGS_PRIV_APX
#undef  ELBOX_LOG_MESSAGE
#undef  ELBOX_MADWIFI
#undef  ELBOX_PROGS_PRIV_ART_AP83
#undef  ELBOX_PROGS_PRIV_ART_AP101
#undef  ELBOX_PROGS_PRIV_BUILDIN_ART
#undef  ELBOX_PROGS_PRIV_ART_PB44
#undef  ELBOX_PROGS_PRIV_ART_DB12X
#undef  ELBOX_PROGS_PRIV_ART_AP123_AR93
#undef  ELBOX_PROGS_PRIV_MADWIFI_AP83
#undef  ELBOX_PROGS_PRIV_MADWIFI_CAVIUM
#undef  ELBOX_PROGS_PRIV_MADWIFI_FUSION_CAVIUM
#define ELBOX_PROGS_PRIV_WLAN_W_PARTITION 1
#undef  ELBOX_PROGS_PRIV_MADWIFI_FUSION_CAVIUM_SEATTLE
#undef  ELBOX_PROGS_PRIV_MADWIFI_LSDK_WLAN_V9
#undef  ELBOX_RALINK_WIFI
#undef  ELBOX_PROGS_PRIV_RALINK_INIC
#undef  ELBOX_RT2860V2
#undef  ELBOX_RT2561
#undef  ELBOX_BROADCOM_WIFI
#define ELBOX_PROGS_PRIV_RALINK_DRIVER 1

/* Select Driver */
#define ELBOX_PROGS_PRIV_RALINK_RT3883_3662_SMART_ANTENNA 1

/* Select AP/STA driver */
#define ELBOX_PROGS_PRIV_RALINK_RT3883_3662_SMART_ANTENNA_AP 1
#define ELBOX_PROGS_PRIV_RALINK_RT3883_3662_SMART_ANTENNA_AP_CONFIG_FILE "config.alpha_dap1522b.mk"
#define ELBOX_PROGS_PRIV_RALINK_RT3883_3662_SMART_ANTENNA_AP_SW_PORT_BASE_QOS 1
#define ELBOX_PROGS_PRIV_RALINK_RT3883_3662_SMART_ANTENNA_STA 1
#define ELBOX_PROGS_PRIV_RALINK_RT3883_3662_SMART_ANTENNA_STA_CONFIG_FILE "config.alpha.sta_dap1522b.mk"
#define ELBOX_PROGS_PRIV_RALINK_RT3883_3662_STA_DHCP_UDPCHECKSUM_REBUILD 1
#undef  ELBOX_PROGS_PRIV_RALINK_RT3352_WIFI_DRIVER_2_5_0_4
#undef  ELBOX_PROGS_PRIV_RALINK_RT3572_AP_DRIVER_2_5_0_2
#undef  ELBOX_PROGS_PRIV_RALINK_RT5592_V2700
#undef  ELBOX_PROGS_PRIV_RALINK_APP
#undef  ELBOX_PROGS_PRIV_RALINK_RT3090
#undef  ELBOX_PROGS_PRIV_RALINK_RT3883_3662
#undef  ELBOX_SAMSUNG_EZLINK
#undef  ELBOX_PROGS_PRIV_UPNPKITS
#undef  ELBOX_PROGS_PRIV_NEAPS
#undef  ELBOX_PROGS_PRIV_NEAPS_ARIES
#define ELBOX_PROGS_PRIV_AP_NEAP 1
#define ELBOX_PROGS_PRIV_AP_NEAPS 1
#define ELBOX_PROGS_PRIV_AP_NEAPS_DCC 1
#undef  ELBOX_PROGS_PRIV_AP_NEAPS_RGDB_LOC

/* AP Neap Server Class Configuration */
#define CONFIG_AP_NEAPS_INTERNET 1
#define CONFIG_AP_NEAPS_WIRELESS 1
#define CONFIG_AP_NEAPS_RESIDENTIAL_GATEWAY 1
#undef  CONFIG_AP_NEAP_AP_ARRAY
#undef  ELBOX_PROGS_PRIV_AP_NEAPC
#undef  ELBOX_PROGS_PRIV_IGMP
#undef  ELBOX_PROGS_PRIV_IGMPPROXY
#undef  ELBOX_PROGS_PRIV_MRD
#undef  ELBOX_PROGS_PRIV_SCHEDULED
#undef  ELBOX_PROGS_PRIV_COMMON_SCRIPTS
#undef  ELBOX_PROGS_PRIV_DHCPXMLPATCH
#define ELBOX_PROGS_PRIV_UPDATELEASES 1
#undef  ELBOX_PROGS_PRIV_MTDTEST
#undef  ELBOX_PROGS_PRIV_PORTT
#undef  ELBOX_PROGS_PRIV_NETSTAR
#undef  ELBOX_PROGS_PRIV_RESOLVED
#undef  ELBOX_PROGS_PRIV_PROXYD
#undef  ELBOX_PROGS_PRIV_MIIICASA
#undef  ELBOX_DDNS
#undef  ELBOX_PROGS_PRIV_BDTOOL
#undef  ELBOX_PROGS_PRIV_BDCFG
#define ELBOX_PROGS_PRIV_LLD2D 1
#undef  ELBOX_PROGS_PRIV_CMCGI
#undef  ELBOX_PROGS_PRIV_ART
#undef  ELBOX_PROGS_PRIV_YAHOO_WIDGET
#undef  ELBOX_PROGS_PRIV_TR069_CLIENT
#undef  ELBOX_PROGS_PRIV_TR069V3_CLIENT
#undef  ELBOX_PROGS_PRIV_TRAFFICCTRL
#undef  ELBOX_PROGS_PRIV_ALPHA_HOTPLUG
#undef  ELBOX_PROGS_PRIV_WCN_UFD
#undef  ELBOX_PROGS_PRIV_MADWIFI_DUALBAND
#undef  ELBOX_PROGS_PRIV_ALPHA_NLS_DRV
#undef  ELBOX_PROGS_PRIV_WPSTOOLS
#undef  ELBOX_PROGS_PRIV_WPS2TOOLS
#undef  ELBOX_PROGS_PRIV_WPA_SUPPLICANT
#undef  ELBOX_PROGS_PRIV_WPA_SUPPLICANT_0_5
#undef  ELBOX_PROGS_PRIV_CAPWAP
#undef  ELBOX_PROGS_PRIV_CLI
#undef  ELBOX_FIRMWARE_HEADER_VERSION_CONTROL
#undef  ELBOX_PROGS_PRIV_CLI_SEATTLE
#undef  ELBOX_WLXMLPATCHV2
#define ELBOX_PROGS_PRIV_NETBIOS 1
#define ELBOX_PROGS_PRIV_NETBIOS_ARIES 1
#undef  ELBOX_PROGS_PRIV_NETBIOS_LINK_LOCAL_IP
#undef  ELBOX_PROGS_PRIV_NETBIOS_MULTI_NAME
#undef  ELBOX_PROGS_PRIV_ETHLINK
#undef  ELBOX_PROGS_PRIV_SENDMAIL
#undef  ELBOX_PROGS_PRIV_STATIC_DHCP
#define ELBOX_PROGS_PRIV_SERVD 1
#define ELBOX_PROGS_PRIV_CGIBIN_ARIES 1

/* CGI bin of Aries */

/* CGI Programs */
#define CONFIG_CGIBIN_ARIES_PHPCGI 1
#define CONFIG_CGIBIN_ARIES_PHPCGI_MAXFILESIZE 0x80000
#define CONFIG_CGIBIN_ARIES_SESSIONCGI 1
#define CONFIG_CGIBIN_ARIES_CAPTCHACGI 1
#define CONFIG_CGIBIN_ARIES_HEDWIGCGI 1
#define CONFIG_CGIBIN_ARIES_PIGWIDGEONCGI 1
#define CONFIG_CGIBIN_ARIES_SERVICECGI 1
#define CONFIG_CGIBIN_ARIES_CONNTRACKCGI 1
#define CONFIG_CGIBIN_ARIES_FILELOAD 1
#define CONFIG_CGIBIN_ARIES_DLCONFIG_FILE "config.dcf"
#define CONFIG_CGIBIN_ARIES_FILELOAD_MAXCODESIZE 0x100000
#define CONFIG_CGIBIN_ARIES_FWUPDATE_MAXCODESIZE 0x3A0000
#define CONFIG_CGIBIN_ARIES_FWUPDATE_MTDBLOCK "/dev/mtdblock/2"
#define CONFIG_CGIBIN_ARIES_FWUPDATER 1
#define CONFIG_CGIBIN_ARIES_HNAP 1

/* UPnP components */
#define CONFIG_CGIBIN_ARIES_SSDPCGI 1
#define CONFIG_CGIBIN_ARIES_SOAPCGI 1
#define CONFIG_CGIBIN_ARIES_GENACGI 1
#undef  CONFIG_CGIBIN_ARIES_WFADEV
#undef  CONFIG_CGIBIN_ARIES_WFANOTIFY
#undef  CONFIG_CGIBIN_ARIES_SCANDIR
#undef  ELBOX_PROGS_PRIV_UPNP_AV
#define ELBOX_PROGS_PRIV_VERIFICATION_CODE 1
#undef  ELBOX_PROGS_PRIV_CLONED
#undef  ELBOX_PROGS_PRIV_LOGD
#define ELBOX_PROGS_PRIV_LOGD_AP 1
#define CONFIG_LOGD_PHP_HELPER "/etc/services/LOG/logd_helper.php"
#define CONFIG_LOGD_KLOG_INF_TABLE_SIZE 8
#undef  ELBOX_PROGS_PRIV_IODATA_QUICKCOPY
#undef  ELBOX_PROGS_PRIV_IODATA_QUICKCOPY_CLIENT
#undef  ELBOX_PROGS_PRIV_DDNSD
#undef  ELBOX_PROGS_PRIV_DDPD
#undef  ELBOX_PROGS_PRIV_DHCPPLUS
#undef  ELBOX_PROGS_PRIV_STARSPEED
#undef  ELBOX_PROGS_PRIV_TRAP_MONITOR
#undef  ELBOX_PROGS_PRIV_AUTOREKEY
#undef  ELBOX_PROGS_PRIV_ALPHA_3GTOOL
#undef  ELBOX_PROGS_PRIV_WEBREDIRECT
#undef  ELBOX_PROGS_PRIV_WFI_INV
#undef  ELBOX_PROGS_PRIV_IGMP_2_6_27
#undef  ELBOX_PROGS_PRIV_USBOVERIP
#undef  ELBOX_PROGS_PRIV_RALINK_REPEATER
#undef  ELBOX_PROGS_PRIV_RALINK_SCAN
#define ELBOX_PROGS_PRIV_LLMNRESP 1
#undef  ELBOX_PROGS_PRIV_NAMERESOLV
#undef  ELBOX_PROGS_PRIV_WEPCLIENTINFOPATCH
#undef  ELBOX_PROGS_PRIV_MADWIFI_AR724X
#define ELBOX_UPDATEWIFISTATS 1
#define ELBOX_PROGS_PRIV_UPDATEWIFISTATS_RALINK 1
#undef  ELBOX_PROGS_PRIV_UPDATEWIFISTATS_ATHEROS
#undef  ELBOX_PROGS_PRIV_UPDATEWIFISTATS_BROADCOM

/* Ralink model selection */
#define ELBOX_PROGS_PRIV_UPDATEWIFISTATS_RALINK_RT2800 1
#define ELBOX_PROGS_PRIV_UPDATEWIFISTATS_RALINK_DEFAULT 1
#undef  ELBOX_PROGS_PRIV_UPDATEWIFISTATS_RALINK_SDK3300_V2XXX
#undef  ELBOX_PROGS_PRIV_RTSTAD
#undef  PROGS_PRIV_WAPI_SECURITY_VERSION
#undef  PROGS_PRIV_ATHEROS_SECURITY_VERSION
#define ELBOX_PROGS_PRIV_HOSTAPD_WPS 1

/* Support Samsung Auto Provision */
#undef  ELBOX_PROGS_PRIV_SUPPORT_AUTO_PROVISION

/* Support RealTek RT8198 */
#undef  ELBOX_PROGS_PRIV_REALTEK_RT8198

/* Support detail log for hostapd */
#define ELBOX_PROGS_PRIV_AP_SYSLOG 1

/* Support WPS 2.0 */
#undef  ELBOX_PROGS_PRIV_WPS_2_0
#undef  ELBOX_PROGS_PRIV_APMODULE_FOR_ZOOM_NETWORKS
#undef  ELBOX_PROGS_PRIV_APMODULE_FOR_WINHAP
#undef  ELBOX_UPDATESITESURVEY
#undef  ELBOX_BCM_WPS_PBC
#undef  ELBOX_PROGS_PRIV_USBMOUNT
#undef  ELBOX_PROGS_PRIV_SHAREPORT_PLUS
#undef  ELBOX_PROGS_PRIV_CYASSL
#undef  ELBOX_PROGS_PRIV_ALPHA_STUNNEL
#undef  ELBOX_PROGS_PRIV_WEB_FILE_ACCESS
#undef  ELBOX_PROGS_PRIV_PLC

/* Common library configuration */
#define ELBOX_COMLIB_MEM_HELPER_DISABLE 1
