#
# Created by David Hsieh <david_hsieh@alphanetworks.com>
#

-include ../../path.mk
-include ../../.config

TARGET	:= buildimg v2image packimgs genbn bcat alpha_pack

HGCC	:= gcc
HLD		:= gcc
HCFLAGS	:= -Wall -I$(TOPDIR)/include
HLDFKAGS:=


all:

###################################################################
# execution

packimgs:

buildimg:

v2image: 

genbn:

bcat:

alpha_pack:


###################################################################
# objects



###################################################################
# clean
clean:

gpl:


.PHONY: all clean gpl
